export const AllTypes = {
    SET_TOKEN: "SET_TOKEN",
    UPDATE_VIEW: "UPDATE_VIEW",
    FETCH_ASYNC_START: "FETCH_ASYNC_START",
    FETCH_FEATURED_SUCCESS: "FETCH_FEATURED_SUCCESS",
    FETCH_FEATURED_ERROR:"FETCH_FEATURED_ERROR",
    FETCH_NEW_RELEASES_SUCCESS: "FETCH_NEW_RELEASES_SUCCESS",
    FETCH_NEW_RELEASES_ERROR:"FETCH_NEW_RELEASES_ERROR",
    FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
    FETCH_GENRES_ERROR:"FETCH_GENRES_ERROR"
  }
 
    

  
